name: Build OptiBest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # JAR DOSYASI EKSİK OLDUĞU İÇİN BU ADIM ŞART:
    - name: Setup Gradle Wrapper
      run: gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build OptiBest JAR
      run: ./gradlew build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: OptiBest-1.0
        path: build/libs/*.jar
        
